// <auto-generated />
using System;
using InterviewTask.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewTask.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterviewTask.Models.UserDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime?>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MgrId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Seniority")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tbl_users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 105,
                            DOJ = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Accounts",
                            EmpCode = "ACC0034",
                            FirstName = "Sanjay",
                            LastLogin = new DateTime(2016, 5, 2, 14, 25, 34, 0, DateTimeKind.Unspecified),
                            LastName = "Agarwal",
                            MgrId = 78,
                            Role = "A/C",
                            Seniority = 5.0800000000000001,
                            UserName = "Acc0185"
                        },
                        new
                        {
                            UserId = 106,
                            DOJ = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Accounts",
                            EmpCode = "ACC0598",
                            FirstName = "Amit",
                            LastName = "Sharma",
                            MgrId = 105,
                            Role = "Asst.",
                            Seniority = 8.1500000000000004,
                            UserName = "Acc0567"
                        },
                        new
                        {
                            UserId = 428,
                            DOJ = new DateTime(2018, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Development",
                            EmpCode = "DEV0833",
                            FirstName = "Lokesh",
                            LastLogin = new DateTime(2020, 9, 19, 10, 45, 12, 0, DateTimeKind.Unspecified),
                            LastName = "Kumar",
                            Role = "VP",
                            Seniority = 1.05,
                            UserName = "Dev0476"
                        },
                        new
                        {
                            UserId = 568,
                            DOJ = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Admin",
                            EmpCode = "ADM0048",
                            FirstName = "Naresh",
                            MgrId = 78,
                            Role = "Exec",
                            Seniority = 9.0099999999999998,
                            UserName = "ADM6633"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
